theme: jekyll-theme-cayman
title: Will’s Inventory
repotitle: Will’s Inventory
author: Will (WHASonYT#5995)
url: https://willm.ga
favicon: https://vignette.wikia.nocookie.net/eastenders/images/9/92/UKTV_channel_W_logo.png
